import { createContext, useContext, useState } from 'react'
import type { ReactNode } from 'react'

type Lang = 'zh' | 'en' | 'ja' | 'ko'

interface LanguageContextType {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: string) => string
}

const translations: Record<Lang, Record<string, string>> = {
  zh: {
    slogan: '我们终将会在极光下重逢',
    nav1: '角色设定', nav2: '角色物料', nav4: '官方联动', nav5: '角色编年史',
    nav6: '强度专区', nav7: '黑泥区', nav8: '投稿区', nav9: '账户中心', nav10: '个人中心', nav11: '祝福区',
    nav12: '生贺应援', nav13: '意见反馈', nav14: '生贺/赞助',
    nav15: '自定义页面', nav16: '砂砂想说',
    home: '首页',
    copyright: '非商用粉丝站 · 版权归米哈游及原作者所有 · 本站与米哈游官方无关',
    footer_slogan: '我们终将会在极光下重逢',
    lang_zh: '中文', lang_en: 'English', lang_ja: '日本語', lang_ko: '한국어',
    home_hero_sub: '崩坏：星穹铁道 · 砂金 Aventurine 全球粉丝应援站',
    quick_cards: '快速导航',
    join_us: '加入应援',
    latest_update: '最新动态',
    character_info: '角色档案',
    story_pinakonia: '匹诺康尼剧情',
    voice_lines: '语音台词',
    lore: '人物考据',
    official_art: '官方原画',
    merch: '应援物料',
    preview: '预览',
    by_artist: '画师：',
    collab_store: '联名门店',
    merch_catalog: '周边图鉴',
    timeline: '时间轴',
    team_guide: '配队攻略',
    lc_guide: '光锥推荐',
    relic_guide: '遗器搭配',
    strength_compare: '强度对比',
    discussion: '留言讨论',
    vent_board: '吐槽留言板',
    vent_notice: '请理性讨论，禁止人身攻击',
    submit_photo: '线下应援实拍投稿',
    artist_name: '画师/作者署名',
    description: '作品描述',
    upload_image: '上传图片',
    submit_btn: '提交投稿',
    login: '登录', register: '注册',
    change_pwd: '修改密码', bind_email: '绑定邮箱', privacy: '隐私设置',
    my_posts: '我的投稿', my_favorites: '我的收藏',
    no_posts: '暂无投稿', no_favorites: '暂无收藏',
    character_full_name: '砂金 · Aventurine',
    character_subtitle: '匹诺康尼 · IPC 战略投资部长',
    loading: '加载中...',
    empty_state: '内容正在准备中，敬请期待',
    view_more: '查看更多',
    back_home: '返回首页',
    blessings_title: '祝福区 - 愿极光照亮你的旅途',
    blessings_subtitle: '为砂金献上最真挚的祝福',
    blessings_input_placeholder: '写下你对砂金的祝福...',
    blessings_send: '发送祝福',
    blessings_empty: '还没有祝福，来当第一个留下祝福的人吧',
    blessings_like: '赞',
    blessings_time: '刚刚',
    contact_us: '联系我们',
    contact_title: '联系方式',
    page_title_support: '✨ 生贺应援',
    page_subtitle_support: '全球粉丝线下应援活动汇总',
    join_support_title: '🎂 加入应援',
    join_support_1: '我可以提供大屏',
    join_support_2: '我可以提供无料',
    join_support_3: '我可以提供场地支持',
    join_support_4: '我可以提供经济上的支持',
    join_support_5: '我要参加生贺产出接龙',
    join_support_6: '我要参加线上生日会',
    join_support_7: '我想举行线下生咖/only',
    search_city: '🔍 搜索城市筛选应援活动...',
    all_cities: '全部城市',
  },
  en: {
    slogan: 'We will reunite beneath the aurora',
    nav1: 'Character', nav2: 'Materials', nav4: 'Collaborations', nav5: 'Chronicle',
    nav6: 'Strength', nav7: 'Rant Zone', nav8: 'Submit', nav9: 'Account', nav10: 'Profile', nav11: 'Blessings',
    nav12: 'Birthday Support', nav13: 'Feedback', nav14: 'Sponsorship',
    nav15: 'Custom Page',
    home: 'Home',
    copyright: 'Non-commercial fan site · All rights reserved by miHoYo · Not affiliated with miHoYo',
    footer_slogan: 'We will reunite beneath the aurora',
    lang_zh: '中文', lang_en: 'English', lang_ja: '日本語', lang_ko: '한국어',
    home_hero_sub: 'Honkai: Star Rail · Aventurine Global Fan Support Station',
    quick_cards: 'Quick Navigation',
    join_us: 'Join Support',
    latest_update: 'Latest Updates',
    character_info: 'Character Profile',
    story_pinakonia: 'Penacony Story',
    voice_lines: 'Voice Lines',
    lore: 'Lore & Analysis',
    official_art: 'Official Artwork',
    merch: 'Support Merch',
    preview: 'Preview',
    by_artist: 'Artist: ',
    collab_store: 'Collab Stores',
    merch_catalog: 'Merchandise Catalog',
    timeline: 'Timeline',
    team_guide: 'Team Comp Guide',
    lc_guide: 'Light Cone Guide',
    relic_guide: 'Relic Guide',
    strength_compare: 'Strength Comparison',
    discussion: 'Discussion Board',
    vent_board: 'Rant Board',
    vent_notice: 'Please discuss rationally. Personal attacks are not allowed.',
    submit_photo: 'Submit Event Photos',
    artist_name: 'Artist / Author Name',
    description: 'Work Description',
    upload_image: 'Upload Image',
    submit_btn: 'Submit',
    login: 'Login', register: 'Register',
    change_pwd: 'Change Password', bind_email: 'Bind Email', privacy: 'Privacy Settings',
    my_posts: 'My Posts', my_favorites: 'My Favorites',
    no_posts: 'No posts yet', no_favorites: 'No favorites yet',
    character_full_name: 'Aventurine',
    character_subtitle: 'Penacony · IPC Strategic Investment Dept.',
    loading: 'Loading...',
    empty_state: 'Content coming soon',
    view_more: 'View More',
    back_home: 'Back to Home',
    blessings_title: 'Blessings - May the Aurora Light Your Path',
    blessings_subtitle: 'Send your blessings to Aventurine',
    blessings_input_placeholder: 'Write your blessing for Aventurine...',
    blessings_send: 'Send Blessing',
    blessings_empty: 'No blessings yet. Be the first!',
    blessings_like: 'Like',
    blessings_time: 'Just now',
    contact_us: 'Contact Us',
    contact_title: 'Contact Information',
    page_title_support: '✨ Birthday Support',
    page_subtitle_support: 'Global Fan Offline Support Events',
    join_support_title: '🎂 Join Support',
    join_support_1: 'I can provide large screens',
    join_support_2: 'I can provide freebies',
    join_support_3: 'I can provide venue support',
    join_support_4: 'I can provide financial support',
    join_support_5: 'I want to join the fanwork relay',
    join_support_6: 'I want to join the online birthday party',
    join_support_7: 'I want to host an offline cafe/only event',
    search_city: '🔍 Search city to filter...',
    all_cities: 'All Cities',
  },
  ja: {
    slogan: 'オーロラの下で再会する',
    nav1: 'キャラクター', nav2: '素材', nav4: '公式コラボ', nav5: '年代記',
    nav6: '強度', nav7: '愚痴コーナー', nav8: '投稿', nav9: 'アカウント', nav10: 'プロフィール', nav11: '祝福',
    nav12: '誕生日応援', nav13: 'ご意見', nav14: '誕生日/スポンサー',
    nav15: 'カスタムページ',
    home: 'ホーム',
    copyright: '非商用ファンサイト · すべての権利はmiHoYoに帰属 · miHoYo公式とは無関係',
    footer_slogan: 'オーロラの下で再会する',
    lang_zh: '中文', lang_en: 'English', lang_ja: '日本語', lang_ko: '한국어',
    home_hero_sub: '崩壊：スターレイル · アヴェンチュリン グローバルファン応援サイト',
    quick_cards: 'クイックナビ',
    join_us: '応援に参加',
    latest_update: '最新情報',
    character_info: 'キャラクター情報',
    story_pinakonia: 'ペナコニーストーリー',
    voice_lines: 'ボイス台詞',
    lore: 'キャラクター考察',
    official_art: '公式イラスト',
    merch: '応援グッズ',
    preview: 'プレビュー',
    by_artist: 'イラスト：',
    collab_store: 'コラボ店舗',
    merch_catalog: 'グッズカタログ',
    timeline: 'タイムライン',
    team_guide: '編成ガイド',
    lc_guide: '光円錐ガイド',
    relic_guide: '遺物ガイド',
    strength_compare: '強度比較',
    discussion: 'ディスカッション',
    vent_board: '愚痴掲示板',
    vent_notice: '理性的な議論をお願いします。個人攻撃は禁止です。',
    submit_photo: 'イベント写真投稿',
    artist_name: 'イラストレーター名',
    description: '作品説明',
    upload_image: '画像をアップロード',
    submit_btn: '投稿する',
    login: 'ログイン', register: '登録',
    change_pwd: 'パスワード変更', bind_email: 'メール連携', privacy: 'プライバシー設定',
    my_posts: '投稿作品', my_favorites: 'お気に入り',
    no_posts: '投稿がまだありません', no_favorites: 'お気に入りがまだありません',
    character_full_name: 'アヴェンチュリン',
    character_subtitle: 'ペナコニー · IPC 戦略投資部長',
    loading: '読み込み中...',
    empty_state: 'コンテンツ準備中',
    view_more: 'もっと見る',
    back_home: 'ホームに戻る',
    blessings_title: '祝福エリア - オーロラが道を照らしますように',
    blessings_subtitle: 'アヴェンチュリンに祝福を',
    blessings_input_placeholder: 'アヴェンチュリンへの祝福を書いてください...',
    blessings_send: '祝福を送る',
    blessings_empty: 'まだ祝福がありません。最初の祝福を残しましょう！',
    blessings_like: 'いいね',
    blessings_time: 'たった今',
    contact_us: 'お問い合わせ',
    contact_title: '連絡先',
    page_title_support: '✨ 誕生日応援',
    page_subtitle_support: '世界中のファンによるオフライン応援イベント',
    join_support_title: '🎂 応援に参加',
    join_support_1: '大画面を提供できます',
    join_support_2: '無料グッズを提供できます',
    join_support_3: '会場サポートを提供できます',
    join_support_4: '経済的サポートを提供できます',
    join_support_5: 'ファン作品リレーに参加したい',
    join_support_6: 'オンライン誕生日会に参加したい',
    join_support_7: 'オフラインカフェ/オンリーイベントを開催したい',
    search_city: '🔍 都市で検索...',
    all_cities: 'すべての都市',
  },
  ko: {
    slogan: '오로라 아래서 다시 만나리',
    nav1: '캐릭터', nav2: '자료', nav4: '공식 콜라보', nav5: '연대기',
    nav6: '강도', nav7: '불만 게시판', nav8: '투고', nav9: '계정', nav10: '프로필', nav11: '축복',
    nav12: '생일 응원', nav13: '의견', nav14: '생일/후원',
    nav15: '커스텀 페이지',
    home: '홈',
    copyright: '비상업적 팬사이트 · 모든 권리는 miHoYo에 귀속 · miHoYo 공식과 무관',
    footer_slogan: '오로라 아래서 다시 만나리',
    lang_zh: '中文', lang_en: 'English', lang_ja: '日本語', lang_ko: '한국어',
    home_hero_sub: '붕괴: 스타레일 · 아벤투린 글로벌 팬 응원 사이트',
    quick_cards: '빠른 이동',
    join_us: '응원 참여',
    latest_update: '최신 업데이트',
    character_info: '캐릭터 정보',
    story_pinakonia: '페나코니 스토리',
    voice_lines: '보이스 라인',
    lore: '캐릭터 고찰',
    official_art: '공식 일러스트',
    merch: '응원 굿즈',
    preview: '미리보기',
    by_artist: '작가: ',
    collab_store: '콜라보 매장',
    merch_catalog: '굿즈 카탈로그',
    timeline: '타임라인',
    team_guide: '팀 구성 가이드',
    lc_guide: '광추 가이드',
    relic_guide: '유물 가이드',
    strength_compare: '강도 비교',
    discussion: '토론 게시판',
    vent_board: '불만 게시판',
    vent_notice: '이성적인 토론 부탁드립니다. 인신공격 금지.',
    submit_photo: '현장 사진 투고',
    artist_name: '작가명',
    description: '작품 설명',
    upload_image: '이미지 업로드',
    submit_btn: '제출',
    login: '로그인', register: '회원가입',
    change_pwd: '비밀번호 변경', bind_email: '이메일 연동', privacy: '개인정보 설정',
    my_posts: '내 투고 작품', my_favorites: '즐겨찾기',
    no_posts: '아직 투고 작품이 없습니다', no_favorites: '즐겨찾기가 없습니다',
    character_full_name: '아벤투린',
    character_subtitle: '페나코니 · IPC 전략투자부장',
    loading: '로딩 중...',
    empty_state: '콘텐츠 준비 중',
    view_more: '더 보기',
    back_home: '홈으로',
    blessings_title: '축복 구역 - 오로라가 당신의 길을 비추길',
    blessings_subtitle: '아벤투린에게 축복을',
    blessings_input_placeholder: '아벤투린에게 보내는 축복을 작성하세요...',
    blessings_send: '축복 보내기',
    blessings_empty: '아직 축복이 없습니다. 첫 축복을 남겨보세요!',
    blessings_like: '좋아요',
    blessings_time: '방금',
    contact_us: '문의하기',
    contact_title: '연락처',
    page_title_support: '✨ 생일 응원',
    page_subtitle_support: '전 세계 팬 오프라인 응원 이벤트',
    join_support_title: '🎂 응원 참여',
    join_support_1: '대형 스크린을 제공할 수 있습니다',
    join_support_2: '무료 굿즈를 제공할 수 있습니다',
    join_support_3: '장소 지원을 제공할 수 있습니다',
    join_support_4: '경제적 지원을 제공할 수 있습니다',
    join_support_5: '팬 창작 릴레이에 참여하고 싶습니다',
    join_support_6: '온라인 생일 파티에 참여하고 싶습니다',
    join_support_7: '오프라인 카페/온리 이벤트를 개최하고 싶습니다',
    search_city: '🔍 도시로 검색...',
    all_cities: '모든 도시',
  },
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'zh',
  setLang: () => {},
  t: (k) => k,
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('zh')
  const t = (key: string) => translations[lang][key] || translations['zh'][key] || key
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  return useContext(LanguageContext)
}
